### ISSUE TITLE
 file field in email is populated with 'TYPO3\CMS\Form\Mvc\Property\TypeConverter\PseudoFileReference:' as img title

### ISSUE THREAD

**Issue by DrDBanner** [svewap/form_extended#24]
... instead of the filename. The file is attached though.

<img width="559" alt="Bildschirmfoto 2024-06-27 um 14 39 50" src="https://github.com/WapplerSystems/form_extended/assets/25568865/9a0cc7bd-117f-4ae6-8691-6b3ab21f4f32">

```
        type: GridRow
        identifier: gridrow-3
        label: 'Grid: Zeile'
        renderables:
          -
            properties:
              saveToFileMount: '1:/user_upload/formular-ankauf/'
              allowedMimeTypes:
                - image/jpeg
                - image/png
                - image/bmp
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '6'
                  xs:
                    numbersOfColumnsToUse: '12'
                  xxl:
                    numbersOfColumnsToUse: '6'
                  xl:
                    numbersOfColumnsToUse: '6'
                  md:
                    numbersOfColumnsToUse: '6'
                  sm:
                    numbersOfColumnsToUse: '6'
              elementDescription: 'Bilder hinzufügen. (jpg,png)'
              multiple: true
            type: ImageUpload
            identifier: imageupload-1
            label: Bilder
          -
            properties:
              saveToFileMount: '1:/user_upload/formular-ankauf/'
              allowedMimeTypes:
                - application/msword
                - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                - application/msexcel
                - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                - application/pdf
                - application/vnd.oasis.opendocument.text
                - application/vnd.oasis.opendocument.spreadsheet-template
              elementDescription: 'Dokumente hinzufügen. (doc,docx,xls,xlsx,pdf,ods,odt)'
              gridColumnClassAutoConfiguration:
                viewPorts:
                  xs:
                    numbersOfColumnsToUse: '12'
                  xxl:
                    numbersOfColumnsToUse: '6'
                  xl:
                    numbersOfColumnsToUse: '6'
                  lg:
                    numbersOfColumnsToUse: '6'
                  md:
                    numbersOfColumnsToUse: '6'
                  sm:
                    numbersOfColumnsToUse: '6'
              multiple: true
            type: FileUpload
            identifier: fileupload-1
            label: Dokumente
```

I am unsure if this within the extension or a core issue.
